### ISSUE TITLE
Very difficult to run

### ISSUE THREAD

**Issue by lrbisolo** [smokelore/UnityPointCloud#1]
Hi, thanks for share!
Its hard to make your project run, can you share the libraries you use?
Like KdTree and C5? The ZigFu I know is proprietary, but another ones have very incompatibilities with your code!
Thank you!

**Comment by ckchow** [comment]
this is part of https://github.com/ckchow/KinectUnity, so there might be some nontrivial coupling between the two projects. We threw it together for a class a while back so it's not really under development. if you just want the renderer you might be able to strip out the references to KdTree and C5 in this project.

**Comment by lrbisolo** [comment]
Oh very thank you!
